name: Terraform

on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello World from project-infrastructure"

  terraform:
    needs: hello_world
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Plan
      run: terraform plan
      continue-on-error: true
